name: Release

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup Atlassian SDK
      run: |
        sudo sh -c 'echo "deb https://packages.atlassian.com/debian/atlassian-sdk-deb/ stable contrib" >>/etc/apt/sources.list'
        wget https://packages.atlassian.com/api/gpg/key/public  
        sudo apt-key add public
        sudo apt-get update
        sudo apt-get install atlassian-plugin-sdk
    - name: Test project
      run: |
        atlas-clean -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B
        atlas-unit-test -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B
    - name: Build package
      run: |
        atlas-package -DskipTests
    - name: Get package name
      id: get-package-name
      run: |
        echo ::set-output name=package-path::$(ls target/*.jar | grep -v test)
        echo ::set-output name=package-name::$(ls target/*.jar | grep -v test | xargs -n 1 basename -s ".jar")
    - name: Create release
      id: create_release
      uses: actions/create-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get-extension-name.outputs.package-name }}
        release_name: ${{ steps.get-extension-name.outputs.package-name }}
        draft: false
        prerelease: false
    - name: Upload release asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ steps.get-package-name.outputs.package-path }}
        asset_name: ${{ steps.get-package-name.outputs.package-name }}.jar
        asset_content_type: application/octet-stream
